//AUTH
export const SIGNIN_USER = 'SIGNIN_USER' as const;
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS' as const;
export const SIGNOUT_USER = 'SIGNOUT_USER' as const;
export const SIGNOUT_USER_SUCCESS = 'SIGNOUT_USER_SUCCESS' as const;
export const REGISTER_USER = 'REGISTER_USER' as const;
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS' as const;
export const REGISTER_RECRUTEUR = 'REGISTER_RECRUTEUR' as const;
export const REGISTER_RECRUTEUR_SUCCESS = 'REGISTER_RECRUTEUR_SUCCESS' as const;
export const GET_INFO_USER_CONNECTED = 'GET_INFO_USER_CONNECTED' as const;
export const GET_INFO_USER_CONNECTED_SUCCESS = 'GET_INFO_USER_CONNECTED_SUCCESS' as const;
export const IS_AUTHENTIFICATED = 'IS_AUTHENTIFICATED' as const;
export const IS_AUTHENTIFICATED_SUCCESS = 'IS_AUTHENTIFICATED_SUCCESS' as const;

//INFO CANDIDAT
export const GET_INFOS_CANDIDAT = 'GET_INFOS_CANDIDAT' as const;
export const GET_INFOS_CANDIDAT_SUCCESS = 'GET_INFOS_CANDIDAT_SUCCESS' as const;
export const UPDATE_CANDIDAT = 'UPDATE_CANDIDAT' as const;
export const UPDATE_CANDIDAT_SUCCESS = 'UPDATE_CANDIDAT_SUCCESS' as const;
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD' as const;
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS' as const;

//INFO RECRUTEUR
export const GET_INFOS_RECRUTEUR = 'GET_INFOS_RECRUTEUR' as const;
export const GET_INFOS_RECRUTEUR_SUCCESS = 'GET_INFOS_RECRUTEUR_SUCCESS' as const;
export const UPDATE_RECRUTEUR = 'UPDATE_RECRUTEUR' as const;
export const UPDATE_RECRUTEUR_SUCCESS = 'UPDATE_RECRUTEUR_SUCCESS' as const;
